### ISSUE TITLE
Migration to v14

### ISSUE THREAD

**Issue by p-tombez** [camptocamp/odoo-cloud-platform#204]
TODO:

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

GLOBAL:
- [x] #209 

MODULES TO MIGRATE:
 - [x] attachment_s3 #210 
 - [x] attachment_swift #210 
 - [x] base_attachment_object_storage #210 
 - [x] base_fileurl_field #210 
 - [x] cloud_platform #211 
 - [x] cloud_platform_exoscale #211 
 - [x] cloud_platform_ovh #211 
 - [x] logging_json #205 
 - [x] monitoring_log_requests #212
 - [x] monitoring_statsd #207 
 - [x] monitoring_status #208 
 - [x] session_redis #206 
 - [ ] test_base_fileurl_field

**Comment by leemannd** [comment]
Missing module `test_base_fileurl_field`. IDK on which project it is used, but could be added right?

**Comment by p-tombez** [comment]
@leemannd It was not even migrated from 12 to 13, not sure if it is needed...

**Comment by leemannd** [comment]
@p-tombez I know it wasn't, but it implements tests for a module that was migrated in V13 & V14. I think it is a good idea to migrate it (and the work today to have it migrated is about 5 minutes).

Sidenote my comment isn't ment to be blocking. But the cost is low and this should add security on a linked module.

**Comment by leemannd** [comment]
@p-tombez It was migrated, but never reviewed ;) https://github.com/camptocamp/odoo-cloud-platform/pull/190
Seems to be the good moment to take the opportunity to do it right?
