### ISSUE TITLE
Migration to version 13.0

### ISSUE THREAD

**Issue by grindtildeath** [camptocamp/odoo-cloud-platform#84]
TODO:

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

GLOBAL:
- [x] #81 :heavy_check_mark: 

MODULES TO MIGRATE:
 - [x] attachment_s3 #82  :heavy_check_mark:
 - [x] attachment_swift #85  :heavy_check_mark:
 - [x] base_attachment_object_storage #83  :heavy_check_mark:
 - [x] base_fileurl_field #86  :heavy_check_mark:
 - [x] cloud_platform #87  :heavy_check_mark:
 - [x] cloud_platform_exoscale #88  :heavy_check_mark:
 - [x] cloud_platform_ovh #93  :heavy_check_mark:
 - [x] logging_json #89  :heavy_check_mark:
 - [x] monitoring_log_requests #94  :heavy_check_mark:
 - [x] monitoring_statsd #90  :heavy_check_mark:
 - [x] monitoring_status #91  :heavy_check_mark:
 - [x] session_redis #92  :heavy_check_mark:
 - [ ] test_base_fileurl_field

**Comment by asaunier** [comment]
What about `test_base_fileurl_field`?

**Comment by Tonow-c2c** [comment]
@asaunier it's was not required for my project so I didn't take time to upgrade it

**Comment by Tonow-c2c** [comment]
@guewen the symfact project work on ch platform so can we merge all PR related to this platform ?
